
package fl.site.wsclient.calc.fight;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FightService", targetNamespace = "http://ws.calc.fl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FightService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<fl.site.wsclient.calc.fight.Fighter>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fight", targetNamespace = "http://ws.calc.fl/", className = "fl.site.wsclient.calc.fight.Fight")
    @ResponseWrapper(localName = "fightResponse", targetNamespace = "http://ws.calc.fl/", className = "fl.site.wsclient.calc.fight.FightResponse")
    @Action(input = "http://ws.calc.fl/FightService/fightRequest", output = "http://ws.calc.fl/FightService/fightResponse")
    public List<Fighter> fight(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Fighter> arg0);

}
