
package fl.site.wsclient.calc.fight;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FightServiceImplService", targetNamespace = "http://ws.calc.fl/", wsdlLocation = "http://localhost:8015/service/fight?wsdl")
public class FightServiceImplService
    extends Service
{

    private final static URL FIGHTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIGHTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName FIGHTSERVICEIMPLSERVICE_QNAME = new QName("http://ws.calc.fl/", "FightServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8015/service/fight?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIGHTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        FIGHTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public FightServiceImplService() {
        super(__getWsdlLocation(), FIGHTSERVICEIMPLSERVICE_QNAME);
    }

    public FightServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIGHTSERVICEIMPLSERVICE_QNAME, features);
    }

    public FightServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, FIGHTSERVICEIMPLSERVICE_QNAME);
    }

    public FightServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIGHTSERVICEIMPLSERVICE_QNAME, features);
    }

    public FightServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FightServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FightService
     */
    @WebEndpoint(name = "FightServiceImplPort")
    public FightService getFightServiceImplPort() {
        return super.getPort(new QName("http://ws.calc.fl/", "FightServiceImplPort"), FightService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FightService
     */
    @WebEndpoint(name = "FightServiceImplPort")
    public FightService getFightServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.calc.fl/", "FightServiceImplPort"), FightService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIGHTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw FIGHTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return FIGHTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
